# version: '3.8'
# services:
#   nginx:
#     build:
#       context: .
#     ports:
#       - 80:80
#     volumes:
#       - ./build:/usr/share/nginx/html
#       - ./default.config:/etc/nginx/conf.d/default.conf
#docker compose -p evosolution-frontend up -d

version: '3.8'
services:
  react-nginx-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    # expose:
    #   - 80
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html
      - ./default.config:/etc/nginx/conf.d/
      - ./certbot/www/:/var/www/certbot/:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
